name: 'Setup SSH'
description: 'Configures SSH keys and settings'
inputs:
  ssh_private_key:
    description: 'SSH private key content'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up SSH keys
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_private_key }}" > ~/.ssh/id_clofresvagcupg02
        chmod 600 ~/.ssh/id_clofresvagcupg02

        # Disable strict host key checking using echo commands
        echo "Host *" > ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
        chmod 600 ~/.ssh/config