all:
  hosts:
    bastion:
      ansible_host: {{ BASTION_IP }}
      ansible_user: azureuser
      ansible_ssh_private_key_file: {{ SSH_KEY_PATH }}
      ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'
    reverse_proxy:
      ansible_host: {{ PROXY_IP }}
      ansible_user: azureuser
      ansible_ssh_private_key_file: {{ SSH_KEY_PATH }}
      ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -o StrictHostKeyChecking=accept-new -i {{ SSH_KEY_PATH }} azureuser@{{ BASTION_IP }}"'
    app_server:
      ansible_host: {{ APP_IP }}
      ansible_user: azureuser
      ansible_ssh_private_key_file: {{ SSH_KEY_PATH }}
      ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -o StrictHostKeyChecking=accept-new -i {{ SSH_KEY_PATH }} azureuser@{{ BASTION_IP }}"'
  vars:
    project_name: {{ PROJECT_NAME }}
    storage_account: {{ STORAGE_ACCOUNT }}
    blob_endpoint: {{ BLOB_ENDPOINT }}
    REPO_NAME: {{ REPO_NAME }}
    github_runner_token: {{ RUNNER_TOKEN }}