---
- name: Ensure the bastion host is installed
  hosts: bastion
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - python3-pip
          - python3-venv
          - nginx
          - net-tools
        state: present

    - name: Allow SSH and custom port for bastion
      ufw:
        rule: allow
        port: '{{ item }}'
        proto: tcp
      loop:
        - "22"
        - "2222"

    - name: Enable UFW
      ufw:
        state: enabled

    - name: Ensure SSH service is running
      service:
        name: ssh
        state: started
        enabled: yes

    - name: Set authorized key for azureuser
      authorized_key:
        user: azureuser
        state: present
        key: "{{ lookup('file', ansible_ssh_private_key_file + '.pub') }}"

    - name: Configure SSH to listen on both ports 22 and 2222
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "{{ item }}"
        state: present
      loop:
        - "Port 22"
        - "Port 2222"
      notify: restart sshd

    - name: Create a sentinel file to mark setup as completed
      file:
        path: /etc/ansible_configured
        state: touch
        mode: '0644'
      changed_when: false

  handlers:
    - name: restart sshd
      service:
        name: ssh
        state: restarted