#cloud-config
package_update: true
package_upgrade: true
packages:
  - software-properties-common
  - unzip
  - wget

runcmd:
  - add-apt-repository ppa:dotnet/backports -y
  - apt-get update
  - apt-get install -y aspnetcore-runtime-9.0