#cloud-config
package_update: true # Update all packages
package_upgrade: true # Upgrade all packages
packages:
  - nginx
  - wget
  - unzip
  - software-properties-common

write_files:
  - path: /etc/systemd/system/mywebapp.service
    content: |
      [Unit]
      Description=My .NET Web App
      After=network.target

      [Service]
      WorkingDirectory=/var/www/mywebapp
      ExecStart=/usr/bin/dotnet /var/www/mywebapp/MVC_TestApp.dll
      Restart=always
      RestartSec=10
      User=www-data
      Environment=ASPNETCORE_ENVIRONMENT=Production
      Environment=ASPNETCORE_URLS=http://localhost:5000

      [Install]
      WantedBy=multi-user.target

  - path: /etc/nginx/sites-available/mywebapp
    content: |
      server {
          listen 80;
          location / {
              proxy_pass http://localhost:5000;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection keep-alive;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_cache_bypass $http_upgrade;
          }
      }

  - path: /tmp/setup.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      # set -e  # Exit on error

      echo "Starting setup..."

      # Deploy application
      if [ -f /tmp/mvc_app.zip ]; then
        echo "Deploying application..."
        mkdir -p /var/www/mywebapp
        if ! unzip -o /tmp/mvc_app.zip -d /var/www/mywebapp/; then
          echo "Failed to unzip application"
          exit 1
        fi
        chown -R www-data:www-data /var/www/mywebapp
        chmod -R 755 /var/www/mywebapp
      else
        echo "ERROR: Application package not found!"
        exit 1
      fi

      # Configure and start nginx
      echo "Configuring nginx..."
      mkdir -p /etc/nginx/sites-enabled
      rm -f /etc/nginx/sites-enabled/default
      ln -sf /etc/nginx/sites-available/mywebapp /etc/nginx/sites-enabled/
      if ! systemctl restart nginx; then
        echo "Failed to restart nginx"
        exit 1
      fi

      # Start application service
      echo "Starting application service..."
      systemctl daemon-reload
      if ! systemctl enable mywebapp.service; then
        echo "Failed to enable application service"
        exit 1
      fi
      if ! systemctl start mywebapp.service; then
        echo "Failed to start application service"
        exit 1
      fi

      echo "Setup completed successfully"

runcmd:
  - add-apt-repository ppa:dotnet/backports -y
  - apt-get update
  - apt-get install -y aspnetcore-runtime-9.0
